#!/bin/bash

direction="bottom"
namespace=""
desktop=$(bspc query -D -d)

while getopts ':d:n:g' flag; do
	case "${flag}" in
		d) 
			direction="$OPTARG"
		;;
		g)
			desktop="quakify_global"
		;;
		n)
			namespace="$OPTARG"
		;;
		?)

		;;
  esac
done

echo $desktop"_"$direction"_quaked"$namespace
