#!/bin/bash

file=$(basename $1)
folder=$(cat /dev/shm/pimio_folder)
[[ $1 == *"/edit"* ]] && echo "BROWSING EDIT |"
[[ $1 == *"/potential"* ]] && echo "BROWSING POTENTIAL |"
echo "E: $(find $folder/edit/ -type l -name "*.JPG" | wc -l)"
echo "P: $(find $folder/potential/ -type l -name "*.JPG" | wc -l)"
echo $file
echo $1
echo $file > "$folder"/.pimiofile
[[ -f $folder/edit/$file || ($1 == *"/potential"* && -f $folder/../edit/$file) ]] && echo *EDIT*
[[ -f $folder/potential/$file || ($1 == *"/edit"* && -f $folder/../potential/$file) ]] && echo *POTENTIAL*
