#!/bin/bash

sxhkd &

bspc config border_width        0
bspc config border_radius       5
bspc config window_gap         10

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
#bspc config focus_by_distance   true
bspc config click_to_focus true
bspc config single_monocle true

bspc config focused_border_color \#bbbb99
bspc config presel_border_color \#ffff00

bspc config external_rules_command $BSPWM_SCRIPTS_DIR/multiple_external_rules
$BSPWM_SCRIPTS_DIR/add_external_rule $HOME/scripts/quakify/external_rules
#bspc config external_rules_command scripts/quakify/external_rules

#bspc config top_padding 20
#bspc monitor DVI-1 -d 1 2 3 4 5 6 7 8 9

#bspc config normal_frame_opacity 0.5
#bspc config focused_frame_opacity 0.5

bspc rule -a Gimp follow=on 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Guake state=floating
bspc rule -a Tilda state=floating
bspc rule -a cairo-dock-dialog state=floating
bspc rule -a ardour_plugin_editor state=floating
bspc rule -a Lxappearance desktop='^6'
bspc rule -a Patchage desktop='^6'
bspc rule -a Qsynth desktop=^6
bspc rule -a Boincmgr desktop='^6'
bspc rule -a URxvt:floating state=floating
bspc rule -a Alacritty:floating state=floating
bspc rule -a kitty:floating state=floating
bspc rule -a 'Ardour-4.7.0' state=floating
bspc rule -a Onboard state=floating
bspc rule -a Pinentry state=floating
bspc rule -a Zathura state=tiled

# floating urxvt size {
windowwidth=1000
windowheight=800

screenwidth=$(xdpyinfo  | grep dimensions | awk '{print $2}' | awk -F x '{print $1}')
screenheight=$(xdpyinfo  | grep dimensions | awk '{print $2}' | awk -F x '{print $2}')
windowx=$(("$screenwidth"/2-"$windowwidth"/2))
windowy=$(("$screenheight"/2-"$windowheight"/2))

echo rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"
bspc rule -a URxvt:floating state=floating rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"
# }

export BSPWM_DESKTOP_WALL_WIDTH=3
export BSPWM_DESKTOP_WALL_HEIGHT=2
$BSPWM_SCRIPTS_DIR/desktop_wall init

wmname LG3D
change-wallpaper $HOME/sparkleshark/wallpaper
bspc subscribe node_add node_remove | while read line; do update-wallpaper; done &
bspc subscribe desktop_focus | while read line; do notify-focused-desktop && update-wallpaper; done &

xdotool behave_screen_edge --quiesce 600 --delay 0 top-right exec bin/notify-info &
#(sleep 5 && start_jack) &
#start_jack &
