#! /usr/bin/env python3

import sys

from bspwmpython.querytree import get_tree, path_to_window, follow_path

if len(sys.argv) != 2:
    print('expected exactly one argument (window ID)')
        sys.exit(1)

        tree = get_tree()
        w_id = int(sys.argv[1], 16)
        path = path_to_window(tree, w_id)
        if path is not None:
            axis = follow_path(tree, path[:-1])['splitType'] == 'horizontal'
            index = path[-1] == 'secondChild'
            print(('east', 'south', 'west', 'north')[2 * index + axis])
