#!/bin/bash

notify-focused-desktop &
update-wallpaper &

dirs=( top bottom left right )

for dir in "${dirs[@]}"; do
	win=$(xdotool search --classname --onlyvisible '^_'${dir}'_quaked')
	if [[ -n $win ]]; then 
		xdotool windowactivate $win
		break
	fi
done

